"""added time limit to verbreason question

Revision ID: 47fc92adb0f0
Revises: af3fb153d167
Create Date: 2020-05-25 16:18:49.415572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fc92adb0f0'
down_revision = 'af3fb153d167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verb_reason', sa.Column('time_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verb_reason', 'time_limit')
    # ### end Alembic commands ###
