"""empty message

Revision ID: 6557b5042ecd
Revises: 
Create Date: 2020-05-25 13:11:48.562205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6557b5042ecd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aptitude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('option_one', sa.String(length=140), nullable=True),
    sa.Column('option_two', sa.String(length=140), nullable=True),
    sa.Column('option_three', sa.String(length=140), nullable=True),
    sa.Column('option_four', sa.String(length=140), nullable=True),
    sa.Column('option_five', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aptitude_timestamp'), 'aptitude', ['timestamp'], unique=False)
    op.create_table('set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_name', sa.Text(), nullable=False),
    sa.Column('set_about', sa.Text(), nullable=True),
    sa.Column('setaddedtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_set_setaddedtime'), 'set', ['setaddedtime'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('assessor', sa.Boolean(), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('image_file', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('apt_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apt_answered_by', sa.Integer(), nullable=True),
    sa.Column('apt_question', sa.String(length=140), nullable=False),
    sa.Column('apt_choice', sa.String(length=140), nullable=False),
    sa.ForeignKeyConstraint(['apt_answered_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('setname', sa.String(length=140), nullable=True),
    sa.Column('aptitudefeedback', sa.String(length=140), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('feedback_for', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_for'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_timestamp'), 'feedback', ['timestamp'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_name', sa.Text(), nullable=False),
    sa.Column('setid', sa.Integer(), nullable=True),
    sa.Column('setname', sa.Text(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('quizaddedtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['setid'], ['set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_quizaddedtime'), 'quiz', ['quizaddedtime'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('task_posted_at', sa.DateTime(), nullable=True),
    sa.Column('side_notes', sa.Text(), nullable=False),
    sa.Column('task_completed_by_date', sa.Text(), nullable=True),
    sa.Column('task_for', sa.Integer(), nullable=True),
    sa.Column('task_set', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_for'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_set'], ['set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_task_posted_at'), 'tasks', ['task_posted_at'], unique=False)
    op.create_table('solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Solution', sa.Text(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('problemname', sa.Text(), nullable=False),
    sa.Column('setname', sa.Text(), nullable=True),
    sa.Column('solutionaddedtime', sa.DateTime(), nullable=True),
    sa.Column('problem_answered_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['problem_answered_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_solutionaddedtime'), 'solution', ['solutionaddedtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solution_solutionaddedtime'), table_name='solution')
    op.drop_table('solution')
    op.drop_index(op.f('ix_tasks_task_posted_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_quiz_quizaddedtime'), table_name='quiz')
    op.drop_table('quiz')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_feedback_timestamp'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_table('apt_answer')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_set_setaddedtime'), table_name='set')
    op.drop_table('set')
    op.drop_index(op.f('ix_aptitude_timestamp'), table_name='aptitude')
    op.drop_table('aptitude')
    # ### end Alembic commands ###
