"""added verbal reasoning table

Revision ID: af3fb153d167
Revises: 6557b5042ecd
Create Date: 2020-05-25 13:58:48.345202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3fb153d167'
down_revision = '6557b5042ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verb_reason',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('option_one', sa.String(length=140), nullable=True),
    sa.Column('option_two', sa.String(length=140), nullable=True),
    sa.Column('option_three', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verb_reason_timestamp'), 'verb_reason', ['timestamp'], unique=False)
    op.create_table('verb_reason_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verb_answered_by', sa.Integer(), nullable=True),
    sa.Column('verb_question', sa.String(length=140), nullable=False),
    sa.Column('verb_choice', sa.String(length=140), nullable=False),
    sa.ForeignKeyConstraint(['verb_answered_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verb_reason_answer')
    op.drop_index(op.f('ix_verb_reason_timestamp'), table_name='verb_reason')
    op.drop_table('verb_reason')
    # ### end Alembic commands ###
